# Base on https://github.com/prb112/letsencrypt-pebble/blob/main/docker-compose.yml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lets-encrypt-pebble
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ua
  template:
    metadata:
      name: ua
      labels:
        app: ua
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: custom
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ua
      containers:
      - name: ua
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always